-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-json
    -   id: check-yaml
    -   id: end-of-file-fixer

-   repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: make mypy
      language: system
